### ISSUE TITLE
Introduce a general results plot in TIARA BC

### ISSUE THREAD

**Issue by dodu94** [JADE-V-V/JADE#169]
Currently TIARA BC produces a number of plots like the following:
![image](https://user-images.githubusercontent.com/25747626/232465241-85d60ca2-a40f-4dff-aded-488be8ff9a9e.png)

these are produced at different thickness, distances, off-axis, etc. It would be nice to have a general plot (one for concrete and one for steel) for each source energy (43 and 68 MeV) that summarize visually all these results (the more is geometrically visual the better)

**Comment by Radiation-Transport** [comment]
LIke this for instance which is the common way to report TIARA results.
<img width="229" alt="image" src="https://user-images.githubusercontent.com/48320561/232466477-78cf2383-462c-4326-8aeb-1a515880cd40.png">

**Comment by AlbertoBittes** [comment]
Solved
![image](https://github.com/JADE-V-V/JADE/assets/119672385/49e6e54e-b820-4053-93d2-d37602247bdc)
