### ISSUE TITLE
FNG Bulk blanket shield experiment should have different names in doc

### ISSUE THREAD

**Issue by dodu94** [JADE-V-V/JADE#195]
![image](https://github.com/JADE-V-V/JADE/assets/25747626/b66b6be6-bb73-4046-b78c-b96def7bab9c)

these a three different experiments, there should be a way to differentiate between them.

**Comment by dodu94** [comment]
Or at least should be treated as sub-capters of the same benchmark

**Comment by AlbertoBittes** [comment]
solved
![image](https://github.com/JADE-V-V/JADE/assets/119672385/0fdbefe9-5cc4-4dc0-a892-201d8b00314a)
