### ISSUE TITLE
[Feature request] - selecting libraries is currently unsafe in openMC and Serpent

### ISSUE THREAD

**Issue by dodu94** [JADE-V-V/JADE#214]
**Is your feature request related to a problem? Please describe.**
LibManager.select_lib() method is often called troughout a JADE session. This ensures that the selected library (for assessment or translation) is actually available for the user.

**Describe the solution you'd like**
To be sure that the selection is safe, 2 steps are required:
1) The libraries available for the LibManager are stored in the LibManager.libraries object. For all codes, only libs that are present in the configuration file are checked. For MCNP, it is additionally checked that the lib is indeed present inside the XSDIR file. For OpenMC and Serpent it may not be needed (different paths for different libs) but it should be doubled checked
2) select_lib() now accepts an optional argument wich is the code for which the lib is neeeded (since the list of available libraries may be different for the different codes). By default now it checks in the MCNP libraries available. This allow to restore full MCNP-Windows capabilities. Logic should be added also to perform different checks for the different codes 

**Describe alternatives you've considered**
An alternative solution is to not check what are the available libraries at all and just trust the configuration file + assume that all codes have available the same libraries. Many issues can arise from this though.

**Comment by alexvalentine94** [comment]
Implemented also for Serpent.

**Comment by sbradnam** [comment]
Serpent capability added commit 0b376f832d4376afa43b1b12c82f7bdcbd55b409
