### ISSUE TITLE
[DOC] - improve documentation on new linux configuration file

### ISSUE THREAD

**Issue by AlbertoBittes** [JADE-V-V/JADE#221]
A clearer explanation on how the configuration file has to be set must be added to documentation

For instance, it is not clear what should be done if a code is not used, or if sbatch files are not used.

There's already information on how to fill it, but I think that more explanation is needed

In particular, I would specify what happens if a field is left blank, what are the default options and what happens in the code if some critical parameter is not given

**Comment by JezSw** [comment]
Should this be in the V3.0.0 project?

**Comment by dodu94** [comment]
I agree

**Comment by dodu94** [comment]
To add on this:
- currently the MPI executable prefix option is not documented (and the screenshot of the excel MAIN config. sheet is not up to date
- I am missing some additional details on how the batch template file work, what are the minimum needed parameters etc.

**Comment by alexvalentine94** [comment]
Documentation has been updated regarding the changes to the config and an additional section added in Usage to describe new capability to submit as a job.
