### ISSUE TITLE
[DOC] - Add guidance on the semantic versioning

### ISSUE THREAD

**Issue by dodu94** [JADE-V-V/JADE#225]
# What where you looking for
Semantic versioning meaning should be explained in the doc. 

# Is the information available in the doc but not where you would expect?
not present yet

# Is information completely lacking or partial?
information is completely lacking

# Where would you insert the missing information?
It should be added in the guide for developers

**Comment by JezSw** [comment]
Want to assign this to me and Adam?

**Comment by dodu94** [comment]
yes, it makes sense, thank you. It goes toghether with the summary of new contribution guidelines
