### ISSUE TITLE
[BUG] - Pandas compatability across python versions

### ISSUE THREAD

**Issue by alexvalentine94** [JADE-V-V/JADE#226]
**Describe the bug**
There are differences across python versions in pandas which is used for post processing

**To Reproduce**
Attempting post processing with different python versions.

**Expected behavior**
The post processing relying on pandas needs to be consistent for different python versions

**Screenshots**
N/A

**Desktop (please complete the following information):**
- V3.0.0
- Linux and Windows

**Configuration settings**
Post process

**Additional context**
N/A

**Comment by alexvalentine94** [comment]
@dodu94 did you adress this with 47ebf61?

**Comment by dodu94** [comment]
no, this was solving issues on the experimental post-processing side, while if I remember correctly we opened this issue due to problems in the sphere post-processing

**Comment by sbradnam** [comment]
Sphere postprocessing is now resolved and tested in 669d4d27ca72edece0b3079ddb200e49e41a3441.
