### ISSUE TITLE
[Feature request] - Pre commit hooks for isort and black formatting

### ISSUE THREAD

**Issue by alexvalentine94** [JADE-V-V/JADE#228]
**Is your feature request related to a problem? Please describe.**
Automate the formatting to ensure consistency on all commits.

**Describe the solution you'd like**
Establishing a pre-commit hook. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by JezSw** [comment]
For clarity, I think we're expecting a pre-commit hook to run black and isort. Additional things can be added later using the framework.

**Comment by JezSw** [comment]
@dodu94 @alexvalentine94 , seems I can't close this issue myself :-(.
