### ISSUE TITLE
[Feature request] - Addition of benchmark template

### ISSUE THREAD

**Issue by alexvalentine94** [JADE-V-V/JADE#230]
**Is your feature request related to a problem? Please describe.**
A method for using a templat to describe the addition of a new benchmark.

**Describe the solution you'd like**
New benchmark template. 

**Describe alternatives you've considered**
N/A

**Additional context**
Following the current examples for new features, bugs and merge requests.

**Comment by dodu94** [comment]
Added with commit cb336589638fd2ef434564902047f1f11167f2f9
