### ISSUE TITLE
[BUG] - Sphere and Sphere SDDR post-processing is currently broken

### ISSUE THREAD

**Issue by dodu94** [JADE-V-V/JADE#231]
**Describe the bug**
Sphere and Sphere SDDR benchmarks post-processing for comparison is currently broken. One reason is probably the different behaviour of pandas across different python releases. There may be other additional issues though

**To Reproduce**
compare two different libraries on the Sphere benchmark

**Expected behavior**
post-processing should end gracefully

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: Linux branch
 - Python version 3.7

**Comment by alexvalentine94** [comment]
Sphere single now restored as well as comparison cases (see #255 ). Sphere SDDR also now includes full original functionality. Example outputs from Linux branch:



![Image](https://github.com/JADE-V-V/JADE/assets/40658938/6b6bc0d3-a682-4696-a89e-9a13145827b3)



![Image](https://github.com/JADE-V-V/JADE/assets/40658938/5934fe31-8712-4873-a336-572856178027)




![Image](https://github.com/JADE-V-V/JADE/assets/40658938/2f38640f-ec41-4877-b38f-2e0d8fbe743f)

**Comment by alexvalentine94** [comment]
Examples from SphereSDDR also now restored. Atlas (now Word only) also replicates previous behavior - example below is for sphere leakage. Also included is new sheet added for reporting number of standard deviations from the mean of reference library. 



![Image](https://github.com/JADE-V-V/JADE/assets/40658938/c40e5759-b091-48d0-8a5d-d72fa0e40e91)



![Image](https://github.com/JADE-V-V/JADE/assets/40658938/8ad73bf7-9347-4d46-81bc-ab377b033a16)



![Image](https://github.com/JADE-V-V/JADE/assets/40658938/7605c790-c86b-4c90-b502-a3c52cb493dc)



![Image](https://github.com/JADE-V-V/JADE/assets/40658938/d99729c4-6754-4992-9fc4-bb416f3aae60)
