### ISSUE TITLE
[Feature request] - prioritize testing for the sphereoutput module

### ISSUE THREAD

**Issue by dodu94** [JADE-V-V/JADE#233]
**Is your feature request related to a problem? Please describe.**
There has been a lot of changes recently on the sphereout.py module and unit test coverage on this is quite small (around 11%).

**Describe the solution you'd like**
Adding tests to this module should be prioritized since the Sphere is the heart of the v3.0.0 release

**Comment by alexvalentine94** [comment]
Coverage somewhat improved with 03b24d2 and 425520f (~15% improvement). Further work to be done.

**Comment by sbradnam** [comment]
Now up to 71% coverage with 669d4d27ca72edece0b3079ddb200e49e41a3441. Adequate for V3.0, further SDDR tests to be added for V3.1.
