### ISSUE TITLE
[Feature request] - Cross section library availability for Serpent 

### ISSUE THREAD

**Issue by alexvalentine94** [JADE-V-V/JADE#235]
**Is your feature request related to a problem? Please describe.**
Currently only the MCNP xsdir is examined to see what cross sections are available. Serpent cross sections are only looked at in the cross section file. 

**Describe the solution you'd like**
The Serpent xsdir should also be checked.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A.

**Comment by sbradnam** [comment]
Added now 0b376f832d4376afa43b1b12c82f7bdcbd55b409
