### ISSUE TITLE
[Feature request] - An utility is needed to put weight windows files that are distributed separately into the proper folders

### ISSUE THREAD

**Issue by AlbertoBittes** [JADE-V-V/JADE#237]
**Is your feature request related to a problem? Please describe.**
In the new release WW files will be stored in the same folder as the original input, while before they were all together in a single folder

**Describe the solution you'd like**
An utility is needed to place such files in the correct folders once the user receives the WW package

**Comment by JezSw** [comment]
@AlbertoBittes I just scanned this and wasn't quite clear what the logic of this is? I'm assuming the output should be be something like:

- input_dir
|- input_1
|- input_2
\- weighted_windows
 |- input_weight_1
 |- input_weight_2

And I'm guessing the inputs will be:
input_dir (from above without the weighted dir)
weighted_window_dir (as recieved?)

Mainly asking as if this is defined I might be able to help if I have some time.

**Comment by dodu94** [comment]
EDIT: it appears that maybe we can store the WW files directly with git using git large files. To be confirmed.
