### ISSUE TITLE
[DOC] - Custom benchmark guidelines should be revised

### ISSUE THREAD

**Issue by dodu94** [JADE-V-V/JADE#241]
# What where you looking for
The documentation related to inserting a custom benchmark to JADE should be revised and updated according to the new v3.0.0 capabilities and folder structure. [link here](https://jade-a-nuclear-data-libraries-vv-tool.readthedocs.io/en/linux/dev/insertbenchmarks.html)

# Is the information available in the doc but not where you would expect?
Documentation is available in the doc but is not up to date with v3.0.0

# Is information completely lacking or partial?
see above

# Where would you insert the missing information?
[here](https://jade-a-nuclear-data-libraries-vv-tool.readthedocs.io/en/linux/dev/insertbenchmarks.html)

**Comment by alexvalentine94** [comment]
Documentation revised.
