### ISSUE TITLE
Change maker type in experimental benchmark

### ISSUE THREAD

**Issue by Radiation-Transport** [JADE-V-V/JADE#242]
**Is your feature request related to a problem? Please describe.**
With multiple libraries with similar results, the difference between libraries cannot be appreciated in this type of graph.
![image](https://github.com/JADE-V-V/JADE/assets/48320561/3df8fe3d-fe51-4e8b-9cd4-97b2b471b205)

**Describe the solution you'd like**
Implement a different marker type per evaluation

**Describe alternatives you've considered**
Leave as it is.

**Additional context**
N/A

**Comment by AlbertoBittes** [comment]
Solved
![image](https://github.com/JADE-V-V/JADE/assets/119672385/bb6bd23a-2a9e-4ba3-bb8a-1751b553bc1f)

**Comment by Radiation-Transport** [comment]
Well done!!!
