### ISSUE TITLE
[BUG] - Default values for experimental benchmarks in main config needs to be restored

### ISSUE THREAD

**Issue by dodu94** [JADE-V-V/JADE#248]
**Describe the bug**
The default value of NPS for the many experimental benchmarks right now is set to 100 an needs to be restore to more sensible values. Moreover, the name of the sheet should be corrected from "computational" to "experimental".

**To Reproduce**
default settings are wrong

**Expected behavior**
The name at the top of the sheet should be corrected and more sensible values (i.e., that can guarantee good statistics) should be set as default NPS in many benchmarks.

**Screenshots**
![image](https://github.com/JADE-V-V/JADE/assets/25747626/498c2234-8e81-42c1-8e52-3a3f195195c1)

**Comment by alexvalentine94** [comment]
d82cb9c partially solves this - corrected the heading for experimental benchmarks tab. NPS values just need to be revised if @AlbertoBittes is happy to take a look.

**Comment by AlbertoBittes** [comment]
Solved
