### ISSUE TITLE
[Feature request] - Add in Sphere typical materials CaF2 and W 

### ISSUE THREAD

**Issue by Radiation-Transport** [JADE-V-V/JADE#251]
**Is your feature request related to a problem? Please describe.**
Two important materials as the CaF2 and W are absent in the Sphere leakage test. These are fundamental in new ITER baseline and figure out possible discrepancies in TLD detector responses.

**Describe the solution you'd like**
Add in the Sphere leakage test two new typical materials CaF2 and W both with natural abundances.

**Describe alternatives you've considered**
Leave the Sphere leakage test as it is now.

**Additional context**

**Comment by dodu94** [comment]
We should add all materials used for recent activation studies as a minimum

**Comment by AlbertoBittes** [comment]
Solved for CaF2 and W
