### ISSUE TITLE
[BUG] - Sphere Excel post-processing requires fix

### ISSUE THREAD

**Issue by AlbertoBittes** [JADE-V-V/JADE#255]
**Describe the bug**
Fixes to be done on excel post-processing of sphere:
1. Differences are not provided in % (I think the table 'Global Quick Results' provides wrong results consequently) and show up with too many decimal digits
2. Gamma flux is not in coarse bin structure
3. In row 9 it is missing the old header row:
![image](https://github.com/JADE-V-V/JADE/assets/119672385/97f704a9-3495-4f77-be57-0a5308e1ce45)
    Without it, it is not clear of which quantity the energy bins are.
4. Preferred structure for the columns is 'Neutron flux in energy bins', 'Gamma flux in energy bins', all other integral quantities. Or at least put integral quantities and binned fluxes together, for the sake of visualization.

Also, some secondary style fixes are suggested:
5. The first column is unused and should be removed (secondary problem)
6. Not all values are centered in the cells (secondary problem)
7. Header row 10 should be vertically aligned (secondary problem)

**To Reproduce**
Post-process Sphere leakage benchmark with whatever library

**Expected behavior**
Recover the previous appearance of sphere leakage benchmark excel post-processing

**Screenshots**
![image](https://github.com/JADE-V-V/JADE/assets/119672385/06809b4e-f7ab-4608-995b-fc9e79754911)
![image](https://github.com/JADE-V-V/JADE/assets/119672385/ac1a4b0e-316f-4d41-b2a3-607b2d562d61)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version current linux branch

**Comment by alexvalentine94** [comment]
Thanks @AlbertoBittes . We will address this. Most of the stuff you raised has been fixed for the Sphere SDDR which I was planning to extend to the Sphere (part of #231). I think it is valuable to also have this dedicated more specific issue.

**Comment by alexvalentine94** [comment]
Sphere comparison Excel sheets restored. Should adress all of your points @AlbertoBittes. Example using some dummy data below.  

![image](https://github.com/JADE-V-V/JADE/assets/40658938/d078dcbc-d8d6-43f6-b64b-f3765327e211)
