### ISSUE TITLE
[BUG] - Missing tally relative error cutoff for materials in sphere benchmark

### ISSUE THREAD

**Issue by AlbertoBittes** [JADE-V-V/JADE#259]
**Describe the bug**
When MCNP inputs of the Sphere Leakage benchmark are generated, the stop card with tally relative error cutoff should be put as specified in the benchmark configuration file MaterialsSettings.csv. This doesn't occur, and the STOP CTME card (non-linux branches)/ STOP NPS card (linux branch) is put instead. 

**To Reproduce**
Generate MCNP inputs for Sphere Leakage Benchmark

**Expected behavior**
Correct STOP card should be set. For Linux version, if other codes don't allow this, set the configuration file differently

**Screenshots**
![image](https://github.com/JADE-V-V/JADE/assets/119672385/ca0bc44f-beff-494a-99c0-43cd7dc570bf)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version all

**Configuration settings**
This occurs with default sphere config file

**Comment by dodu94** [comment]
STOP card is not supported anymore, I think in the end we agreed on keeping only the NPS for better compatibility through codes
