### ISSUE TITLE
[Feature request] - Update doc strings to reflect code changes

### ISSUE THREAD

**Issue by alexvalentine94** [JADE-V-V/JADE#263]
**Is your feature request related to a problem? Please describe.**
A lot of the docstrings are now outdated due to major JADE revisions.

**Describe the solution you'd like**
Updates performed reflecting new function definitions.

**Describe alternatives you've considered**
Not changing.

**Comment by alexvalentine94** [comment]
Relates specifically to expoutput.py

**Comment by trin-wheeler** [comment]
Docstrings updated for expoutput.py, sphereoutput.py and output.py
