### ISSUE TITLE
[BUG] - Incorrect labelling on plots

### ISSUE THREAD

**Issue by alexvalentine94** [JADE-V-V/JADE#269]
**Describe the bug**
The label on certain figures in the Word output is incorrect. 

**To Reproduce**
Running Sphere SDDR with isotopes and materials. 

**Expected behavior**
Correct labeling

**Screenshots**
Aluminium isotope label on concrete plot. 

![image](https://github.com/JADE-V-V/JADE/assets/40658938/b02f15dd-e008-4562-99c1-e65eb14c8009)

**Desktop (please complete the following information):**
 - OS: Linux
 - Observed in 'old' JADE version and 'new'.

**Comment by dodu94** [comment]
I think this has been fixed at some point, even if I do not exactly remember when. Sure thing is that post-processing with #310 give the correct labels
