### ISSUE TITLE
[BUG] - FNG-W TLD simulations end for bad trouble with MCNP

### ISSUE THREAD

**Issue by dodu94** [JADE-V-V/JADE#275]
**Describe the bug**
The FNG-W TLD simulation with different libraries appear to end abruptly due to a bad trouble fatal error in MCNP

**To Reproduce**
for example:
1. run assessment of FNG-W with MCNP
2. chose whatever nuclear data library

**Expected behavior**
Run should be terminated when NPS is reached

**Screenshots**
![image](https://github.com/JADE-V-V/JADE/assets/25747626/3f5c4e48-1b29-4330-a2d9-b711b2f549db)

**Desktop (please complete the following information):**
 - OS: Linux
 - JADE Version v3.0.0 (and previous)

**Configuration settings**
sufficient including FNG-W in the mcnp assessment

**Comment by AlbertoBittes** [comment]
I remember facing this, don't know why it appears. While I was doing some testing on FNG-Bulk Blanket (not W) for TLDs, I remember using this CUT card:
CUT:P   4E+10  1E-3
Please try and let me know if it works in your case, in that case I'll update the inputs in our archive

**Comment by dodu94** [comment]
From Japanese colleagues it appears that changing the PHYS card from 16 yo 20 MeV should solve the issue. More testing is needed.

**Comment by dodu94** [comment]
Removing the PHYS card completely appears to solve the issue
