### ISSUE TITLE
Automatic creation of the XS plot for suspected cases

### ISSUE THREAD

**Issue by Radiation-Transport** [JADE-V-V/JADE#30]
- **Currrent situation:** If there are strange errors in the ZAID, no possible reasons are listed.
- **Possible development:** If there are strange errors in the ZAID, JADE automatically creates plot of the XS. Cases should be defined. It could de done as utility to read the post-processing implemented in the Excel, creating a minor PDF Atlas

**Comment by dodu94** [comment]
This has been substituted by the capability of JADE to plot XS toghether with experimental data on request
