### ISSUE TITLE
[New Benchmark] - introduce new benchmark for code comparison

### ISSUE THREAD

**Issue by alexvalentine94** [JADE-V-V/JADE#327]
## Is the new benchmark computational or experimental?

- [x] Computational

## Is this a MultiTest or a normal Test?
Normal.

## Give a concise description of the benchmark
As there are limitations to the different tally types that are implemented in different transport codes, I suggest that for the purpose of development we contrive a new benchmark with a consistent cross code tally set. 

Propose to introduce the simplified tokamak model which is a 60 degree sector model of a tokamak with homogenised representations of major components out to the bioshield. This has been used extensively in the past for code benchmarking. We can derive a tally list to be consistent across MCNP, OpenMC and Serpent. 

## Does the benchmark needs new types of plots?
Can use existing plot types.

## Can the benchmark be used for all codes implemented in JADE or for a specific subset?
Intention of this benchmark is to be used by all.

## Can inputs of this benchmark be freely re-distributed?
- [x] yes
- [] no

## Additional information/context
This will provide the basis for development of methods needed to process outputs across different codes for benchmarks beyond the sphere. Will serve as a demonstration of JADE capabilities before working on other benchmarks within the limitations of supported tally types.

**Comment by alexvalentine94** [comment]
As the benchmark will be open, it makes sense to host here: https://github.com/IAEA-NDS/open-benchmarks/tree/main

@dodu94 what do you think?

**Comment by dodu94** [comment]
Absolutely! we track here the addition using the specific projects but ultimately the input itself will be added to the IAEA repo. For SINBAD derived benchmarks we are still waiting from NEA for the new version of SINBAD in git and for all others (like the C-model for instance) we are working on setting up a gitlab at F4E

**Comment by dodu94** [comment]
We can close this @alexvalentine94 right?

**Comment by alexvalentine94** [comment]
Resolved in #330
